---

- name: create release config dir
  ansible.builtin.file:
    path: "{{ release_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True
  tags: [ release ]

- name: download release
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ lookup('ansible.builtin.url', item.url, split_lines=False) | regex_replace('/usr/bin/', '/usr/local/bin/') }}"
    force: True
    owner: root
    group: root
    mode: 0644
  become: True
  loop:
    - { url: "{{ release_service_url }}", dest: "{{ release_service_dest }}" }
    - { url: "{{ release_config_url }}", dest: "{{ release_config_dest }}" }
  tags: [ release ]

- name: enable release service
  ansible.builtin.systemd:
    name: "{{ release_service_name }}"
    daemon_reload: True
    enabled: True
  become: True
  tags: [ release ]

- name: create release config dir
  ansible.builtin.file:
    path: "{{ release_kubernetes_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True
  tags: [ release ]

# Explicitly create this, otherwise non-control plane nodes might spam log
- name: create release manifests dir
  ansible.builtin.file:
    path: "{{ release_kubernetes_dir }}/manifests"
    state: directory
    owner: root
    group: root
    mode: 0700
  become: True
  tags: [ release ]
