---

- name: create release config dir
  ansible.builtin.file:
    path: "{{ release_kubelet_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True

- name: download release
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ lookup('ansible.builtin.url', item.url, split_lines=False) | regex_replace('/usr/bin/', '/usr/local/bin/') }}"
    force: True
    owner: root
    group: root
    mode: 0644
  become: True
  loop:
    - url: "{{ release_kubelet_service_url }}"
      dest: "{{ release_kubelet_service_dest }}"
    - url: "{{ release_kubelet_config_url }}"
      dest: "{{ release_kubelet_config_dest }}"

- name: enable kubelet service
  ansible.builtin.systemd:
    name: "{{ release_kubelet_service_name }}"
    daemon_reload: True
    enabled: True
  become: True

- name: create kubernetes config dir
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True

- name: create kubernetes manifests dir
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    owner: root
    group: root
    mode: 0700
  become: True
