---

- name: kubeadm modprobe
  ansible.builtin.command: "modprobe {{ item | quote }}"
  become: True
  loop: "{{ kubeadm_modules }}"
  tags: [ kubeadm ]

- name: kubeadm sysctl reload
  ansible.builtin.command: "sysctl -p /etc/sysctl.d/90-kubeadm.conf"
  become: True
  tags: [ kubeadm ]
