---

- name: download kubelet
  ansible.builtin.get_url:
    url: "{{ kubelet_url }}"
    dest: "{{ common_dir }}/kubelet"
    checksum: "{{ common_checksum_type }}:{{ kubelet_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True
