---

# kubectl is a binary release too
kubectl_url: "https://dl.k8s.io/release/v{{ kubectl_version }}\
  /bin/{{ common_system }}/{{ common_architecture }}/kubectl"

# Like the other kubes
kubectl_checksum: "{{ lookup('ansible.builtin.url', kubectl_checksum_url) }}"

kubectl_checksum_url: "{{ kubectl_url }}.{{ common_checksum_type }}"
