---

cilium_cli_repo: cilium/cilium-cli

cilium_cli_archive_dest: "{{ cache_dir }}/{{ cilium_cli_archive_url | basename }}"

cilium_cli_archive_checksum_url: "{{ cilium_cli_archive_url }}.{{ common_checksum_type }}sum"

cilium_cli_archive_checksum: "{{ lookup('ansible.builtin.url', cilium_cli_archive_checksum_url).split() | first }}"

cilium_cli_archive_url: "https://github.com/{{ cilium_cli_repo }}\
  /releases/download/v{{ cilium_cli_version }}\
  /cilium-{{ common_system }}-{{ common_architecture }}.tar.gz"
