---

- name: download cilium-cli archive
  ansible.builtin.get_url:
    url: "{{ cilium_cli_archive_url }}"
    dest: "{{ cilium_cli_archive_dest }}"
    checksum: "{{ common_checksum_type }}:{{ cilium_cli_archive_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True
  tags: [ cilium, cilium-cli ]

- name: unarchive cilium-cli
  ansible.builtin.unarchive:
    src: "{{ cilium_cli_archive_dest }}"
    dest: "{{ common_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  become: True
  tags: [ cilium, cilium-cli ]

- name: template cilium-cli profile
  ansible.builtin.template:
    src: cilium.profile.j2
    dest: /etc/profile.d/cilium.sh
    owner: root
    group: root
    mode: 0644
  become: True
  tags: [ cilium, cilium-cli ]
