---

cni_plugins_repo: containernetworking/plugins

cni_plugins_archive_url: "https://github.com/{{ cni_plugins_repo }}\
  /releases/download/v{{ cni_plugins_version }}\
  /cni-plugins-{{ common_system }}-{{ common_architecture }}-v{{ cni_plugins_version }}.tgz"

cni_plugins_archive_dest: "{{ cache_dir }}/{{ cni_plugins_archive_url | basename }}"

cni_plugins_archive_checksum_url: "{{ cni_plugins_archive_url }}.{{ common_checksum_type }}"

cni_plugins_archive_checksum: "{{ lookup('ansible.builtin.url', cni_plugins_archive_checksum_url).split() | first }}"

cni_plugins_dir: /opt/cni/bin
