---

cni_plugins_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"
cni_plugins_system: "{{ ansible_system | lower }}"

cni_plugins_archive_url: "https://github.com/containernetworking/plugins\
  /releases/download/v{{ cni_plugins_version }}\
  /cni-plugins-{{ cni_plugins_system }}-{{ cni_plugins_architecture }}-v{{ cni_plugins_version }}.tgz"
cni_plugins_archive_dest: "{{ archives_dir }}/{{ cni_plugins_archive_url | basename }}"
cni_plugins_archive_checksum_type: sha256
cni_plugins_archive_checksum_url: "{{ cni_plugins_archive_url }}.{{ cni_plugins_archive_checksum_type }}"
cni_plugins_archive_checksum: "{{ lookup('ansible.builtin.url', cni_plugins_archive_checksum_url).split() | first }}"

cni_plugins_dir: /opt/cni/bin
