---

- ansible.builtin.stat:
    path: "{{ cni_plugins_version_dest }}"
  register: cni_plugins_version_stat

- ansible.builtin.slurp:
    path: "{{ cni_plugins_version_dest }}"
  register: cni_plugins_version_slurp
  when: cni_plugins_version_stat.stat.exists

- ansible.builtin.debug:
    msg: "cni-plugins: actual = {{ __cni_plugins_version }}, desired = {{ cni_plugins_version }}, upgrade = {{ cni_plugins_upgrade }}"

- name: download cni-plugins archive
  ansible.builtin.get_url:
    url: "{{ cni_plugins_archive_url }}"
    dest: "{{ cni_plugins_archive_dest }}"
    checksum: "{{ cni_plugins_archive_checksum_type }}:{{ cni_plugins_archive_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True

- name: create cni-plugins dir
  ansible.builtin.file:
    path: "{{ cni_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True

- name: unarchive cni-plugins
  ansible.builtin.unarchive:
    src: "{{ cni_plugins_archive_dest }}"
    dest: "{{ cni_plugins_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  become: True

- name: record installed cni-plugins version
  ansible.builtin.copy:
    content: "{{ __cni_plugins_version }}"
    dest: "{{ cni_plugins_version_dest }}"
    owner: root
    group: root
    mode: "0644"
  become: True
