---

- name: download kubectl binary
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ common_dir }}/kubectl"
    checksum: "{{ common_checksum_type }}:{{ kubectl_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True

- name: template kubectl profile
  ansible.builtin.template:
    src: kubectl.profile.j2
    dest: /etc/profile.d/kubectl.sh
    owner: root
    group: root
    mode: 0644
  become: True
