---

- name: download kubectl binary
  ansible.builtin.get_url:
    url: "{{ kubectl_binary_url }}"
    dest: "{{ kubectl_binary_dest }}"
    checksum: "{{ kubectl_binary_checksum_type }}:{{ kubectl_binary_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True
