---

runc_repo: opencontainers/runc

# runc is released directly as a binary
runc_url: "https://github.com/{{ runc_repo }}/releases/download/v{{ runc_version }}/runc.{{ common_architecture }}"

# Replace the last part of the URL to get the checksum URL
runc_checksum_url: "{{ runc_url | dirname }}/runc.{{ common_checksum_type }}sum"

# The checksums are all in a single file, so use a regex to look up the correct one
runc_checksum: "{{ lookup(
  'ansible.builtin.url', runc_checksum_url, split_lines=False
) | regex_search(runc_checksum_regex, '\\1', multiline=True) }}"

runc_checksum_regex: '^([a-z0-9]+)\s+runc\.{{ runc_architecture }}$'
