---

containerd_repo: containerd/containerd

containerd_archive_url: "https://github.com/{{ containerd_repo }}\
  /releases/download/v{{ __containerd_version }}\
  /containerd-{{ __containerd_version }}-{{ containerd_system }}-{{ containerd_architecture }}.tar.gz"

containerd_archive_dest: "{{ cache_dir }}/{{ containerd_archive_url | basename }}"

containerd_archive_checksum_url: "{{ containerd_archive_url }}.{{ common_checksum_type }}sum"

containerd_archive_checksum: "{{ lookup('ansible.builtin.url', containerd_archive_checksum_url).split() | first }}"

containerd_service_url: "https://raw.githubusercontent.com/containerd/containerd/v{{ containerd_version }}/containerd.service"

containerd_service_name: "{{ containerd_service_url | basename }}"

containerd_service_dest: "/etc/systemd/system/{{ containerd_service_name }}"

containerd_config_dir: /etc/containerd

containerd_config_dest: "{{ containerd_config_dir }}/config.toml"
