---

cri_tools_repo: kubernetes-sigs/cri-tools

cri_tools_archive_url: "https://github.com/{{ cri_tools_repo }}\
  /releases/download/v{{ cri_tools_version }}\
  /crictl-v{{ cri_tools_version }}-{{ common_system }}-{{ common_architecture }}.tar.gz"

cri_tools_archive_dest: "{{ cache_dir }}/{{ cri_tools_archive_url | basename }}"

cri_tools_archive_checksum_url: "{{ cri_tools_archive_url }}.{{ common_checksum_type }}"

cri_tools_archive_checksum: "{{ lookup('ansible.builtin.url', cri_tools_archive_checksum_url).split() | first }}"
