---

kubeadm_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"
kubeadm_system: "{{ ansible_system | lower }}"
kubeadm_label: stable

kubeadm_binary_url: "https://dl.k8s.io/release/v{{ kubeadm_version }}\
  /bin/{{ kubeadm_system }}/{{ kubeadm_architecture }}/kubeadm"
kubeadm_binary_dest: /usr/local/bin/kubeadm
kubeadm_binary_checksum_type: sha256
kubeadm_binary_checksum_url: "{{ kubeadm_binary_url }}.{{ kubeadm_binary_checksum_type }}"
kubeadm_binary_checksum: "{{ lookup('ansible.builtin.url', kubeadm_binary_checksum_url) }}"

kubeadm_packages:
  - apparmor
  - conntrack
  - ethtool
  - iptables
  - socat

kubeadm_modules:
  - br_netfilter

kubeadm_sysctl_variables:
  net.ipv4.ip_forward: "1"

kubeadm_version_dest: "{{ archives_dir }}/kubeadm.version"

__kubeadm_version: "{{
  kubeadm_version_slurp.content | b64decode
    if not kubeadm_upgrade and kubeadm_version_stat.stat.exists
    else kubeadm_version
  }}"
