---

# Like the other kubes
kubeadm_url: "https://dl.k8s.io/release/v{{ kubeadm_version }}\
  /bin/{{ common_system }}/{{ common_architecture }}/kubeadm"

kubeadm_checksum_url: "{{ kubeadm_url }}.{{ common_checksum_type }}"

kubeadm_checksum: "{{ lookup('ansible.builtin.url', kubeadm_checksum_url) }}"

# Pre-flight checks check at least these packages on Debian
kubeadm_packages:
  - apparmor
  - conntrack
  - ethtool
  - iptables
  - socat

# Pre-flight check checks these modules
kubeadm_modules:
  - br_netfilter

# This might be set automatically, but set it just in case
kubeadm_sysctl_vars:
  net.ipv4.ip_forward: "1"
