---

release_repo: kubernetes/release

# Base URL for the config and service files
release_url: "https://raw.githubusercontent.com/{{ release_repo }}/v{{ release_version }}/cmd/krel/templates/latest"

# This is actually the kubelet service file, but use a separate role for release as it has its own cycle
release_service_url: "{{ release_url }}/kubelet/kubelet.service"
release_service_name: "{{ release_service_url | basename }}"
release_service_dest: /etc/systemd/system/{{ release_service_name }}

# And this is the kubelet service config file
release_config_url: "{{ release_url }}/kubeadm/10-kubeadm.conf"
release_config_dir: /etc/systemd/system/{{ release_service_name }}.d
release_config_dest: "{{ release_config_dir }}/{{ release_config_url | basename }}"

# Just wrap /etc/kubernetes here
release_kubernetes_dir: /etc/kubernetes
