---

- name: download cri-tools
  ansible.builtin.get_url:
    url: "{{ cri_tools_archive_url }}"
    dest: "{{ cri_tools_archive_dest }}"
    checksum: "{{ cri_tools_archive_checksum_type }}:{{ cri_tools_archive_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True

- name: unarchive cri-tools
  ansible.builtin.unarchive:
    src: "{{ cri_tools_archive_dest }}"
    dest: "{{ cri_tools_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  become: True
