---

- name: download cri-tools
  ansible.builtin.get_url:
    url: "{{ cri_tools_url }}"
    dest: "{{ cri_tools_dest }}"
    checksum: "{{ common_checksum_type }}:{{ cri_tools_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True
  tags: [ cri-tools ]

- name: unarchive cri-tools
  ansible.builtin.unarchive:
    src: "{{ cri_tools_dest }}"
    dest: "{{ common_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  become: True
  tags: [ cri-tools ]
