---

- name: download runc
  ansible.builtin.get_url:
    url: "{{ runc_url }}"
    dest: "{{ common_dir }}/runc"
    checksum: "{{ common_checksum_type }}:{{ runc_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True
  tags: [ runc ]
